import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App Sample',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p style={{marginLeft:"10px", backgroundColor:"#ddd"}}>layout section</p>
      <ul className='topnav' style={{display:"flex"}}>
        <li style={{padding:"5px",margin:"10px",listStyleType:"none"}}>
          <Link href="/About">About</Link>          
        </li>
        <li style={{padding:"5px",margin:"10px",listStyleType:"none"}}>
        <Link href="/contact">Contact</Link>
        </li>
        <li style={{padding:"5px",margin:"10px",listStyleType:"none"}}>
        <Link href="/protected/users">users</Link>
        </li>
        <li style={{padding:"5px",margin:"10px",listStyleType:"none"}}>
        <Link href="/products">Products</Link>
        </li>
      </ul>
        {children}</body>
    </html>
  )
}
